# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: [4.1]

    steps:
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Run docker for R 
        uses: docker://larsvilhuber/rmarkdown:v2021-08-19 
        with:
          args: "R -e rmarkdown::render('index.Rmd')"
